<a href="https://colab.research.google.com/github/MPCCoder/Data-Science-e-Modelos-Preditivos/blob/main/Data_Science_e_Modelos_Preditivos_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bem-vindos ao Laboratório de Data Science! 🚀
Nesta segunda parte da sessão, vamos "sujar as mãos" com dados. Vamos utilizar o **Google Colab**, que nos permite executar código **Python 3.11**
 diretamente no browser.

Para executar uma célula de código, basta clicar no botão de "Play" (▶) à esquerda ou usar o atalho `Shift + Enter`.

In [ ]:
# O nosso primeiro código em Python
mensagem = "Olá, equipa! O ambiente Colab está a funcionar perfeitamente."
print(mensagem)

# Um pequeno teste com a nossa realidade industrial
máquinas = 15
sensores_por_maquina = 4
total_sensores = máquinas * sensores_por_maquina

print(f"Temos {total_sensores} sensores a gerar telemetria na fábrica.")

Olá, equipa! O ambiente Colab está a funcionar perfeitamente.
Temos 60 sensores a gerar telemetria na fábrica.

##1. Ligar a nossa "Base de Dados" (Google Drive) 📁
Na prática, os dados vêm de extrações de Business Intelligence ou diretamente das máquinas industriais. Para o Colab conseguir ler os nossos ficheiros (como os CSVs que vamos usar no projeto), precisamos de lhe dar permissão para aceder ao nosso Google Drive.

> Nota: Ao correr a célula abaixo, aparecerá a mensagem "Permit this notebook to access your Google Drive files?". Devem clicar em "Connect to Google Drive" e autorizar o acesso com a vossa conta.

In [3]:
# Permitir que o Colab veja os ficheiros do Google Drive [1]
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
print("Google Drive ligado com sucesso! Já podemos extrair dados.")

Mounted at /content/drive
Google Drive ligado com sucesso! Já podemos extrair dados.



> O exemplo acima é o mais prático para carregarmos os nossos dados gravados no Google Drive, mas para facilidade da formação vamos usar nesta primeira sessão o Github exemplificado mais abaixo. O código a utilizar para ler do drive é:

```
# 1. Definir o caminho para o ficheiro no Google Drive (ajustar conforme necessário)
caminho_ficheiro = '/content/drive/MyDrive/datamining.csv' # Exemplo baseado no material prático [1]

# 2. Ler o ficheiro para a variável 'df' (Dataframe)
try:
    df = pd.read_csv(caminho_ficheiro)
    print("Ficheiro carregado com sucesso!\n")
    
    # 3. Mostrar as primeiras linhas da nossa tabela para verificar os dados
    display(df.head())
    
except FileNotFoundError:
    print("Erro: Ficheiro não encontrado. Verifiquem o caminho do vosso Drive!")

```

##2. O Nosso "Canivete Suíço": Numpy e Pandas 🛠️

Para não termos de programar tudo do zero, a Ciência de Dados vive de bibliotecas prontas a usar.

As duas fundamentais que iniciam o nosso programa são:
* NumPy: O motor matemático para operações rápidas.
* Pandas: A biblioteca principal para manipulação de dados, que permite ler tabelas (DataFrames) de forma muito intuitiva.

In [4]:
# Importação das bibliotecas (é padrão usar as abreviaturas 'np' e 'pd')
import numpy as np
import pandas as pd

print("Pandas e Numpy carregados! Estamos prontos para a Análise de Dados.")

Pandas e Numpy carregados! Estamos prontos para a Análise de Dados.

##3. O Primeiro Contacto com os Dados Reais 📊
Agora vamos ler o nosso primeiro ficheiro (no formato CSV).

O Pandas transforma este ficheiro num DataFrame (uma tabela nativa do Python).

In [13]:
csv_github_url = 'https://raw.githubusercontent.com/MPCCoder/Data-Science-e-Modelos-Preditivos/refs/heads/main/datamining.csv'
df = pd.read_csv(csv_github_url)

print("CSV carregado com sucesso do GitHub!")
df.head(20)

CSV carregado com sucesso do GitHub!

,age,income,frq,rcn,mnt,clothes,kitchen,small_appliances,toys,house_keeping,dependents,per_net_purchase,gender,education,status,description
0,1946,90782.0,33,66,1402,37,5,44,10,3,0.0,19,M,Graduation,Together,Take my money!!
1,1936,113023.0,32,6,1537,55,1,38,4,2,0.0,9,F,PhD,Divorced,Take my money!!
2,1990,28344.0,11,69,44,32,19,24,1,24,1.0,59,M,Graduation,Married,Kind of OK
3,1955,93571.0,26,10,888,60,10,19,6,5,1.0,35,F,Master,NaN,OK nice!
4,1955,91852.0,31,26,1138,59,5,28,4,4,1.0,34,F,Graduation,Together,Take my money!!
5,1982,22386.0,14,65,56,47,2,48,2,1,1.0,67,M,PhD,Single,OK nice!
6,1969,69485.0,18,73,345,71,7,13,1,8,1.0,46,M,Graduation,Together,OK nice!
7,1960,68602.0,5,44,41,84,1,12,2,0,1.0,37,M,Graduation,Together,Horrible
8,1940,109499.0,30,75,1401,38,9,35,9,9,0.0,17,M,Graduation,Divorced,OK nice!
9,1994,23846.0,8,153,19,18,55,17,10,1,1.0,39,F,1st Cycle,Together,Meh...
10,1949,97492.0,20,93,774,37,16,33,9,5,0.0,15,M,Master,Single,OK nice!
11,1957,75436.0,17,32,491,60,4,33,2,1,1.0,29,M,Graduation,Together,OK nice!
12,1954,95586.0,32,54,1407,27,3,39,20,11,0.0,23,F,2nd Cycle,Widow,Take my money!!
13,1979,57997.0,10,28,81,77,0,21,1,0,1.0,52,M,Graduation,Married,Meh...
14,1982,50289.0,10,231,20,46,0,33,16,5,1.0,70,M,PhD,Together,Meh...
15,1992,20043.0,5,37,16,6,28,35,28,3,0.0,51,M,Graduation,Single,Kind of OK
16,1938,112765.0,44,72,2039,19,1,35,14,31,0.0,23,M,2nd Cycle,Together,OK nice!
17,1990,26141.0,8,52,36,19,17,28,23,12,0.0,50,M,Graduation,Together,Meh...
18,1988,40944.0,10,67,52,30,12,46,9,3,1.0,60,M,2nd Cycle,Together,Meh...
19,1947,89755.0,13,44,394,12,4,14,34,36,0.0,15,M,1st Cycle,Married,Meh...

## 4. O Primeiro Raio-X aos Dados (Introdução à EDA) 📊
Para os perfis mais técnicos, queremos saber os tipos de dados que a máquina importou (inteiros, decimais, texto). Para os perfis de negócio e operações, queremos ver resumos estatísticos rápidos para detetar anomalias ou falhas.
Vamos usar dois comandos mágicos do Pandas:
*  **df.info()**: Mostra-nos as colunas, os tipos de dados e se há dados em falta (Missing Values).
*  **df.describe()**: Calcula automaticamente estatísticas descritivas como a média, mínimo, máximo e desvio padrão para todas as colunas numéricas.

In [14]:
print("--- INFORMAÇÃO TÉCNICA DO DATASET ---")
# O info() ajuda-nos a ver se temos valores nulos que precisem de limpeza futura
df.info()

print("\n\n--- ESTATÍSTICAS DESCRITIVAS ---")
# O describe() faz a matemática básica por nós em segundos
display(df.describe())

--- INFORMAÇÃO TÉCNICA DO DATASET ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8998 entries, 0 to 8997
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               8998 non-null   int64
 1   income            8952 non-null   float64
 2   frq               8998 non-null   int64
 3   rcn               8998 non-null   int64
 4   mnt               8998 non-null   int64
 5   clothes           8998 non-null   int64
 6   kitchen           8998 non-null   int64
 7   small_appliances  8998 non-null   int64
 8   toys              8998 non-null   int64
 9   house_keeping     8998 non-null   int64
 10  dependents        8716 non-null   float64
 11  per_net_purchase  8998 non-null   int64
 12  gender            8998 non-null   object
 13  education         8951 non-null   object
 14  status            8821 non-null   object
 15  description       8998 non-null   object
dtypes: float64(2), int64(10), object(4)
memory usage: 1.1+ MB


--- ESTATÍSTICAS DESCRITIVAS ---

,age,income,frq,rcn,mnt,clothes,kitchen,small_appliances,toys,house_keeping,dependents,per_net_purchase
count,8998.000000,8952.000000,8998.000000,8998.000000,8998.000000,8998.000000,8998.000000,8998.000000,8998.000000,8998.000000,8716.000000,8998.000000
mean,1966.059680,69963.550827,19.848077,62.469771,622.162814,50.446655,7.039675,28.524116,7.036897,6.929984,0.707205,42.428984
std,17.296552,27591.556226,10.903435,69.761802,646.768205,23.422249,7.848139,12.586437,7.924422,7.882655,0.455071,18.495742
min,1936.000000,10000.000000,3.000000,0.000000,6.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,4.000000
25%,1951.000000,47741.000000,10.000000,26.000000,63.000000,33.000000,2.000000,19.000000,2.000000,2.000000,0.000000,28.000000
50%,1966.000000,70030.500000,17.000000,53.000000,383.000000,51.000000,4.000000,28.000000,4.000000,4.000000,1.000000,45.000000
75%,1981.000000,92218.000000,28.000000,79.000000,1076.000000,69.000000,10.000000,37.000000,10.000000,9.000000,1.000000,57.000000
max,1996.000000,140628.000000,59.000000,549.000000,3052.000000,99.000000,75.000000,74.000000,62.000000,77.000000,1.000000,88.000000